on:
  schedule:
    - cron: '58 23 * * *' # Run every day at 11:58 PM (UTC)
jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Node.js Script
        run: |
          npm install
          node index.js

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "machariaalex"
          git config user.email "machariaalex456@gmail.com"
          git add .
          git commit -m "Keep alive update"
          git push -u origin HEAD




